#!/usr/bin/env python
# -*- coding:utf-8 -*-
import argparse
import base64
import struct
import sys

def parseArgs():
    # parser para os argumentos
    parser = argparse.ArgumentParser(description="UnderPressure: Comprime textos usando LZW", prog="pressure")
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-c", "--compress", help="Comprime o texto dado", action="store_true")
    group.add_argument("-x", "--extract", help="Decomprime o texto dado", action="store_true")
    parser.add_argument("-b", "--base64", help="Para textos não ASCII, utiliza essa opção para convertê-los para base64 antes", action="store_true")
    parser.add_argument("-v", "--verbose", help="Executa de forma verbosa", action="store_true")
    parser.add_argument("input", type=file, help="Arquivo de texto para ser comprimido")
    parser.add_argument("output", help="Nome do arquivo de saida")
    return parser.parse_args()

def compress(inputFile, base64, output):
    verbose("Comprimindo arquivo", inputFile.name)
    text = inputFile.read()
    # codifica em base64 e compacta
    if(base64):
        text = encodeBase64(text)
    # LZW em si
    dictSize = 256 # tamanho da tabela ASCII
    dictionary = {}
    # xrange usado por performance
    for i in xrange(dictSize):
        dictionary[chr(i)] = i
    compressed = []

    w = ""
    for c in text:
        wc = w + c
        if wc in dictionary:
            w = wc
        else:
            compressed.append(dictionary[w])
            dictionary[wc] = dictSize
            dictSize += 1
            w = c
    if w:
        compressed.append(dictionary[w])

    writeBinaryFile(output, compressed)

def extract(inputFile, base64, output):
    verbose("Descomprimindo arquivo", inputFile.name)
    text = readBinaryFile(inputFile.name)

    # extrai e DEPOIS decodifica do base64
    dictSize = 256
    dictionary = {}
    for i in xrange(dictSize):
        dictionary[i] = chr(i)
    if text:
        w = chr(text.pop(0))
    else:
        raise ValueError, "empty"
    uncompressed = [w]
    for k in text:
        if k in dictionary:
            entry = dictionary[k]
        elif k == len(dictionary):
            entry = w + w[0]
        else:
            # raise ValueError, "Bad compressed k: %d" % k
            pass
        uncompressed.append(entry)
        dictionary[dictSize] = w + entry[0]
        dictSize += 1
        w = entry

    text = ''.join(uncompressed)

    # Decodifica base64
    if(base64):
        text = decodeBase64(text)

    writeFile(output, text)

def encodeBase64(text):
    verbose("Codificando em Base64")
    encoded = base64.b64encode(text)
    verbose("Codificado!")
    return encoded

def decodeBase64(text):
    verbose("Decodificando de Base64")
    decoded = base64.b64decode(text)
    verbose("Decodificado!")
    return decoded

def writeBinaryFile(filename, array):
    verbose("Escrevendo arquivo binário...")
    f = open(filename, "wb")
    for a in array:
        f.write(struct.pack("!I", a))
    f.close()
    verbose("Feito!")

def readBinaryFile(filename):
    f = open(filename, "rb")
    data = []
    byte = []
    for i in range(0,4):
        readChr = f.read(1)
        byte.append('{0:08b}'.format(ord(readChr)))
    data.append(int(''.join(byte), 2))
    while readChr != "":
        byte = []
        for i in range(0,4):
            readChr = f.read(1)
            if readChr != "":
                byte.append('{0:08b}'.format(ord(readChr)))
        if len(byte) > 0:
            data.append(int(''.join(byte), 2))
    f.close()
    return data

def writeFile(filename, text):
    verbose("Escrevendo arquivo de saída")
    f = open(filename, "w")
    f.write(text)
    f.close()
    verbose("Feito")

def main(args):
    if args.compress:
        compress(args.input, args.base64, args.output)
    elif args.extract:
        extract(args.input, args.base64, args.output)
    else:
        print "Nenhuma opção foi escolhida. Saindo."

if __name__ == "__main__":
    args = parseArgs()
    if(args.verbose):
        def verbose(*args):
            for arg in args:
                print arg,
            print
    else:
        verbose = lambda *a: None
    main(args)
